#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_SRC="$ROOT_DIR/skills"
CONFIG_EXAMPLE="$ROOT_DIR/config/project-memory.env.example"

CONFIG_FILE="${PROJECT_MEMORY_CONFIG:-$HOME/.agents/project-memory.env}"
BIN_DIR="${WORK_SKILLS_BIN_DIR:-$HOME/.local/bin}"
AGENTS="${WORK_SKILLS_AGENTS:-all}"
CUSTOM_SKILLS_DIRS=()
NON_INTERACTIVE=0
FORCE_CONFIG=0
WITH_TIMER=0
ENABLE_TIMER=0

if [[ -n "${WORK_SKILLS_SKILLS_DIR:-}" ]]; then
  CUSTOM_SKILLS_DIRS+=("$WORK_SKILLS_SKILLS_DIR")
fi

VAULT="${PROJECT_MEMORY_VAULT:-}"
WORK_ROOT="${PROJECT_MEMORY_WORK_ROOT:-Work}"
REPO_ROOTS="${PROJECT_MEMORY_REPO_ROOTS:-$HOME/git}"
TIMEZONE="${PROJECT_MEMORY_TIMEZONE:-UTC}"
AGENT_SOURCES="${PROJECT_MEMORY_AGENT_SOURCES:-codex,claude,copilot}"
TIMER_TIME="${PROJECT_MEMORY_AUTOJOURNAL_TIME:-15:30}"

usage() {
  cat <<'EOF'
Usage: ./install.sh [options]

Options:
  --non-interactive        Do not prompt. Requires --vault if config is missing.
  --agents LIST            Comma-separated: all,codex,claude,copilot. Default: all
  --skills-dir PATH        Install skills to a custom PATH. Can be repeated.
  --config PATH            Write config to PATH. Default: ~/.agents/project-memory.env
  --vault PATH             Obsidian vault path.
  --work-root NAME         Work folder inside vault. Default: Work
  --repo-roots PATHS       Colon-separated repo roots. Default: $HOME/git
  --timezone TZ            Timezone for notes. Default: UTC
  --agent-sources LIST     Comma-separated: codex,claude,copilot
  --with-timer             Also install optional systemd user timer.
  --enable-timer           Enable timer immediately. Implies --with-timer.
  --timer-time HH:MM       Timer time. Default: 15:30
  --force-config           Overwrite existing config file.
  -h, --help               Show help.
EOF
}

quote_value() {
  printf '%q' "$1"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --non-interactive) NON_INTERACTIVE=1; shift ;;
    --agents) AGENTS="$2"; shift 2 ;;
    --skills-dir) CUSTOM_SKILLS_DIRS+=("$2"); shift 2 ;;
    --config) CONFIG_FILE="$2"; shift 2 ;;
    --vault) VAULT="$2"; shift 2 ;;
    --work-root) WORK_ROOT="$2"; shift 2 ;;
    --repo-roots) REPO_ROOTS="$2"; shift 2 ;;
    --timezone) TIMEZONE="$2"; shift 2 ;;
    --agent-sources) AGENT_SOURCES="$2"; shift 2 ;;
    --with-timer) WITH_TIMER=1; shift ;;
    --enable-timer) WITH_TIMER=1; ENABLE_TIMER=1; shift ;;
    --timer-time) TIMER_TIME="$2"; shift 2 ;;
    --force-config) FORCE_CONFIG=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

if [[ ! -d "$SKILLS_SRC" ]]; then
  echo "Missing skills source: $SKILLS_SRC" >&2
  exit 1
fi

# shellcheck source=scripts/skill-targets.sh
. "$ROOT_DIR/scripts/skill-targets.sh"
work_skills_resolve_skill_dirs "$AGENTS" "${CUSTOM_SKILLS_DIRS[@]}"

if [[ -z "$VAULT" && ! -f "$CONFIG_FILE" && "$NON_INTERACTIVE" -eq 0 ]]; then
  read -r -p "Obsidian vault path: " VAULT
fi

if [[ -z "$VAULT" && ! -f "$CONFIG_FILE" ]]; then
  echo "Vault path required. Pass --vault PATH or create $CONFIG_FILE." >&2
  exit 1
fi

if [[ -n "$VAULT" && ! -d "$VAULT" ]]; then
  echo "Vault path not found: $VAULT" >&2
  echo "Create/open the folder as an Obsidian vault first, then rerun install." >&2
  exit 1
fi

if [[ -n "$VAULT" && ! -d "$VAULT/.obsidian" ]]; then
  echo "WARN Vault has no .obsidian folder: $VAULT" >&2
  echo "WARN This can still work as a Markdown folder, but confirm this is the intended Obsidian vault." >&2
fi

mkdir -p "$BIN_DIR" "$(dirname "$CONFIG_FILE")"

for skills_dir in "${WORK_SKILLS_RESOLVED_DIRS[@]}"; do
  mkdir -p "$skills_dir"
  for item in \
    project-memory-common.md \
    setup-obsidian-work-skills \
    save-work-checkpoint \
    resume-project-context \
    project-completed-summary \
    retro-summary \
    implementation-finder \
    project-autojournal
  do
    rm -rf "$skills_dir/$item"
    cp -R "$SKILLS_SRC/$item" "$skills_dir/$item"
  done
done

install -m 0755 "$ROOT_DIR/scripts/project-autojournal-run" "$BIN_DIR/project-autojournal-run"

if [[ ! -f "$CONFIG_FILE" || "$FORCE_CONFIG" -eq 1 ]]; then
  cp "$CONFIG_EXAMPLE" "$CONFIG_FILE"
  {
    echo "# Generated by work-skills install.sh"
    echo "PROJECT_MEMORY_VAULT=$(quote_value "$VAULT")"
    echo "PROJECT_MEMORY_WORK_ROOT=$(quote_value "$WORK_ROOT")"
    echo "PROJECT_MEMORY_REPO_ROOTS=$(quote_value "$REPO_ROOTS")"
    echo "PROJECT_MEMORY_TIMEZONE=$(quote_value "$TIMEZONE")"
    echo "PROJECT_MEMORY_AGENT_SOURCES=$(quote_value "$AGENT_SOURCES")"
    echo "PROJECT_MEMORY_CODEX_SESSIONS="
    echo "PROJECT_MEMORY_CLAUDE_PROJECTS="
    echo "PROJECT_MEMORY_COPILOT_WORKSPACE_STORAGE="
    echo "PROJECT_MEMORY_COPILOT_GLOBAL_STORAGE="
    echo "PROJECT_MEMORY_AUTOJOURNAL_TIME=$(quote_value "$TIMER_TIME")"
  } > "$CONFIG_FILE"
else
  echo "Config exists, leaving unchanged: $CONFIG_FILE"
fi

if [[ "$WITH_TIMER" -eq 1 ]]; then
  args=(--config "$CONFIG_FILE" --timer-time "$TIMER_TIME")
  if [[ "$ENABLE_TIMER" -eq 1 ]]; then
    args+=(--enable)
  fi
  if [[ "$NON_INTERACTIVE" -eq 1 || "$ENABLE_TIMER" -eq 1 ]]; then
    args+=(--yes)
  fi
  "$ROOT_DIR/scripts/install-autojournal-timer.sh" "${args[@]}"
fi

cat <<EOF
Installed work skills.

Skill targets:
$(printf '  %s\n' "${WORK_SKILLS_RESOLVED_DIRS[@]}")
Config: $CONFIG_FILE
Runner: $BIN_DIR/project-autojournal-run

Next:
  ./doctor.sh
EOF
